//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int orderdetailid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<long> price { get; set; }
        public Nullable<long> sumprice { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
