//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class productprice
    {
        public int productpriceid { get; set; }
        public long productpricepurch { get; set; }
        public long productpricesell { get; set; }
        public string productpricedate { get; set; }
        public string productpricedesc { get; set; }
        public int productid { get; set; }
        public int userid { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
