//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class systempart
    {
        public int systempartid { get; set; }
        public string systempartname { get; set; }
        public string systempartdetail { get; set; }
        public Nullable<int> systempartlevel { get; set; }
    }
}
