//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlog
    {
        public int userlogid { get; set; }
        public string computername { get; set; }
        public string ipaddress { get; set; }
        public string enterdatetime { get; set; }
        public string exitdatetime { get; set; }
        public int userid { get; set; }
    
        public virtual user user { get; set; }
    }
}
