//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_customer
    {
        public int customerid { get; set; }
        public string customername { get; set; }
        public string customerfamily { get; set; }
        public string customertel { get; set; }
        public string customeraddress { get; set; }
        public int userid { get; set; }
        public string username { get; set; }
        public string userfamily { get; set; }
        public string fullname { get; set; }
        public string customerfullname { get; set; }
    }
}
