//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_inventory
    {
        public int inventoryid { get; set; }
        public int inventorycount { get; set; }
        public string inventorydate { get; set; }
        public string inventorydesc { get; set; }
        public int userid { get; set; }
        public int productid { get; set; }
        public string productname { get; set; }
        public string username { get; set; }
        public string userfamily { get; set; }
        public string fullname { get; set; }
        public string inventorystatus { get; set; }
    }
}
