//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace datamodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_users
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string userfamily { get; set; }
        public string usertel { get; set; }
        public Nullable<byte> usergender { get; set; }
        public Nullable<byte> useractive { get; set; }
        public string userusername { get; set; }
        public string userpassword { get; set; }
        public string logindate { get; set; }
        public string gender { get; set; }
        public string active { get; set; }
    }
}
